config/routes.rb
Rails.application.routes.draw do
  resources :items, only: [:index, :new,:create, :edit, :destroy, :update, ] do
    collection do
      get "search"
    end
  end
  
  root to: "items#index"
  
    
     
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :quantity, presence: true
  validates :place, presence: true
  validates :deliverydate, presence: true
  scope :name_like, -> name { where('name like ?', "%#{name}%") if name.present? }
  def self.search(search)
    if search
      Item.where(['content LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  PER = 8
  def index
    @items = Item.page(params[:page]).per(PER)
  end
  
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if  @item.save
      redirect_to root_path
    else
      render  :new
    end
  end


  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       redirect_to root_path
    else
       redirect_to edit_item_path(item.id)
    end
  end

  def search
    @items = Item.where(['name like ?', "%#{params[:search]}%"])
   
  end







  
  private
  def item_params
    # params.permit(:name, :capacity, :until, :quantity, :place, :deliverydate)
    params.require(:item).permit(:name, :capacity, :until, :quantity, :place, :deliverydate)
  end

end

app/controllers/searches_controller.rb
# class SearchesController < ApplicationController
#   def index
#     @items = Item.search(params[:search]).limit(132)
#     @search = params[:search]
#   end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/items/edit.html.haml
= form_with(model: @item, local: true,method: :PATCH ) do |f|
  .edit
    .edit_header
      .edit_header_name
        =link_to "NETASTOCKS",root_path,class:'neta'
    .edit_main
      .edit_main_title
        在庫編集
      .edit_main_box
        .edit_main_box_text
          .box
            .box_box
              = link_to '削除', "/items/#{@item.id}", method: :delete,class: "destroy"
          .form_text
            .field
              %label 材料名
              = f.text_field :name,class: 'text'
            .field
              %label 容量
              = f.number_field :capacity,class: 'text'
            .field
              %label 単位
              = f.select :until,[ ["g","g"], ["kg", "kg"],["t","t"], ["個", "個"],["パック","パック"], ["枚", "枚"]], prompt: "---"
            .field
              %label 個数
              = f.text_field :quantity,class: 'text'
            .field
              %label 場所
              = f.select :place,[ ["プレハブ","プレハブ"], ["リーチイン", "リーチイン"], ["１番冷蔵庫", "１番冷蔵庫"], ["２番冷蔵庫", "２番冷蔵庫"], ["３番冷蔵庫", "３番冷蔵庫"], ["１番冷凍庫", "１番冷凍庫"], ["２番冷凍庫", "２番冷凍庫"] , ["切りネタ冷凍庫", "切りネタ冷凍庫"], ["ハマチ倉庫", "ハマチ倉庫"], ["ネタ切り冷蔵庫", "ネタ切り冷蔵庫"]], prompt: "---"
            .field
              %label 納品日
              = f.text_field :deliverydate,class: 'text'
            .form_text_btn
              = f.submit '変更する',class: :form__btn

app/views/items/index.html.haml
.top
  .top_header
    .top_header_name
      NETASTOCKS
    .top_header_search
      = form_tag(search_items_path,method: :get,class:"a") do
        = text_field_tag :search, "",placeholder:"何かお探しですか？",class: "tag"
        = submit_tag '検索', :name => nil,class: "kensaku"
  .top_main
    .top_main_text
      ネタ在庫一覧
                    
    .top_main_btn
      =link_to "追加",new_item_path
    .top_main_stock
      .top_main_stock_box
        .top_main_stock_box_type
          .type_name
            ネタ名
          .type_capacity
            内容量
          .type_unit
            単位
          .type_quantity
            個数
          .type_place
            場所
          .type_delivery
            納品日
          .type_edit
            編集
        - @items.each do |item|
          .top_main_stock_box_item
            .item_name
              = item.name
            .item_capacity
              = item.capacity
            .item_unit
              = item.until
            .item_quantity
              = item.quantity
            .item_place
              = item.place
            .item_delivery
              = item.deliverydate
            .item_edit
              =link_to "編集","/items/#{item.id}/edit", method: :get
        = paginate @items

app/views/items/new.html.haml
= form_with(url: "/items/create",newmodel: @item, local: true )do |f|
  .new
    .new_header
      .new_header_name
        =link_to "NETASTOCKS",root_path,class:'neta'
    .new_main
      .new_main_title
        在庫追加
      .new_main_box
        .new_main_box_text
          = render 'layouts/error_messages', model: f.object
          .form_text
            .field
              %label 材料名
              = f.text_field :name,class: 'text'
            .field
              %label 容量
              = f.number_field :capacity,class: 'text'
            .field
              %label 単位
              = f.select :until,[ ["g","g"], ["kg", "kg"],["t","t"], ["個", "個"],["パック","パック"], ["枚", "枚"]], prompt: "---"
            .field
              %label 個数
              = f.text_field :quantity,class: 'text'
            .field
              %label 場所
              = f.select :place,[ ["プレハブ","プレハブ"], ["リーチン", "リーチン"], ["１番冷蔵庫", "１番冷蔵庫"], ["２番冷蔵庫", "２番冷蔵庫"], ["３番冷蔵庫", "３番冷蔵庫"], ["１番冷凍庫", "１番冷凍庫"], ["２番冷凍庫", "２番冷凍庫"] , ["切りネタ冷凍庫", "切りネタ冷凍庫"], ["ハマチ倉庫", "ハマチ倉庫"], ["ネタ切り冷蔵庫", "ネタ切り冷蔵庫"]], prompt: "---"
            .field
              %label 納品日
              = f.text_field :deliverydate,class: 'text'
            .form_text_btn
              = f.submit '追加する',class: :form__btn

app/views/items/search.html.haml
.search
  .search_header
    .search_header_name
      =link_to "NETASTOCKS",root_path,class:'neta'
  .search_main
    .search_main_text
      検索結果
    .search_main_stock
      .search_main_stock_box
        .search_main_stock_box_type
          .type_name
            ネタ名
          .search_capacity
            内容量
          .search_unit
            単位
          .search_quantity
            個数
          .search_place
            場所
          .search_delivery
            納品日
          .search_edit
            編集
        - @items.each do |i|
          .search__box
            .search__box__name
              = i.name
            .search__box__capacity
              = i.capacity
            .search__box__unit
              = i.until
            .search__box__quantity
              = i.quantity
            .search__box__place
              = i.place
            .search__box__delivery
              = i.deliverydate
            .search__box___edit
              =link_to "編集","/items/#{i.id}/edit", method: :get
              

app/views/layouts/_error_messages.html.haml
-if @item.errors.any? 
  .alert
    %ul
      -@item.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Stock
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/


  %body
    = yield